### ISSUE TITLE
Erro 'customer_city_name' não pode ficar em branco

### ISSUE THREAD

**Issue by pauloerweber** [BoletoSimples/boletosimples-magento-v1#1]
Ao realizar um pedido com o Boleto Simples como método de pagamento, o boleto não é gerado (apesar do pedido ser efetuado no Magento) e a mensagem abaixo é registrada:
2017-06-09T18:55:02+00:00 DEBUG (7): [Boleto Simples]  'customer_city_name' não pode ficar em branco 

O problema é causado pela função _build_ da classe Codigo5_BoletoSimples_Model_Order_Builder .
O nome da chave está como 'customer_city', porém a API do Boleto Simples espera pela chave com nome 'customer_city_name'.

Corrigir o nome da chave resolveu o erro e o boleto foi gerado corretamente.

**Comment by dhyegofernando** [comment]
Obrigado por reportar @pauloerweber. Já estou fazendo alguns testes para fazer a devida correção se for o caso.

**Comment by dhyegofernando** [comment]
@pauloerweber ficou estimado para ser finalizado dia 20/06. A nível de feedback e conhecimento, qual a loja virtual que você está desenvolvendo? Pode nos mostrar? Adoraríamos ter como portfolio.
